object_preselection:
  Muon:
    pt: 15
    eta: 2.4
    iso: 0.25 #PFIsoLoose
    id: looseId

  Electron:
    pt: 15
    eta: 2.4
    iso: 0.06
    id: mvaFall17V2Iso_WPL

  Jet:
    dr_lepton: 0.4
    pt: 30
    eta: 2.4
    jetId: 2
    puId:
      wp: L
      value: 4
      maxpt: 50.0

  FatJet:
    dr_lepton: 0.8
    pt: 200
    eta: 2.4
    jetId: 2

  GenJet:
    pt: 20
    eta: 2.4

  GenFatJet:
    pt: 20
    eta: 2.4
