object_preselection:
  Muon:
    pt: 15
    eta: 2.4
    iso: 0.25
    id: tightId

  Electron:
    pt: 15
    eta: 2.4   
    id: cutBased

  Jet:
    dr_lepton: 0.4
    pt: 30
    eta: 2.4
    jetId: 2
    puId:
      wp: L
      value: 4
      maxpt: 50.0

  FatJet:
    dr_lepton: 0.8
    pt: 300
    eta: 2.4
    jetId: 2


  GenJet:
    pt: 20
    eta: 2.4

  GenFatJet:
    pt: 20
    eta: 2.4
