plotting_style:
   samples_groups:
     ttHTobb:
       - ttHTobb
     THW:
       - THW
     ttHToNonbb:
       - ttHToNonbb
     WW:
       - WW
       - WZ
       - ZZ       
     TTZToQQ:
       - TTZToQQ
       - TTZtoLLNuNu
       - TTWJetsToQQ
       - TTGJets
       - TTWJetsToLNu
     WJetsToQQ_HT200to400: 
       - WJetsToLNu_HT-200To400
       - WJetsToLNu_HT-600To800
       - WJetsToLNu_HT-800To1200
       - WJetsToLNu_HT-1200To2500
       - WJetsToLNu_HT-2500ToInf
       - WJetsToQQ_HT400to600
       - WJetsToQQ_HT600to800
       - WJetsToQQ_HT800toInf
     DYJetsToLL_M-50:
       - ZJetsToQQ_HT400to600
       - ZJetsToQQ_HT600to800
       - ZJetsToQQ_HT800toInf
       - DYJetsToLL_M-50
     ST_s-channel_4f_leptonDecays:
       - ST_s-channel_4f_leptonDecays
       - ST_t-channel_top_4f_InclusiveDecays
       - ST_t-channel_antitop_4f_InclusiveDecays
       - ST_tW_top_5f_inclusiveDecays
       - ST_tW_antitop_5f_inclusiveDecays
     QCD_HT500to700:  
       - QCD_HT500to700
       - QCD_HT700to1000
       - QCD_HT1000to1500
       - QCD_HT1500to2000
       - QCD_HT2000toInf  
     TTTo2L2Nu:
       - TTTo2L2Nu
     TTToHadronic:
       - TTToHadronic
       - TTToSemiLeptonic
   labels_mc:
      ttHToNonbb: "ttHToNonbb"
      TTTo2L2Nu : "$t\\bar{t}$ Dilepton"
      QCD_HT500to700 : "QCD"
      WJetsToQQ_HT200to400 : "W plus Jets"
      DYJetsToLL_M-50 : "Z/DY plus Jets"
      WW : "Dibosons"
      ST_s-channel_4f_leptonDecays : "Single Top"
      TTZToQQ : "$t\\bar{t}$ plus W/Z/G"
      TTToHadronic : "$t\\bar{t}$ NonDilepton" 


