plotting_style:
   samples_groups:
     TTHtoNonbbandTHW:
       - TTHtoNonbb
       - THW
     TTbarPlusWZ:
       - TTZToQQ
       - TTZtoLLNuNu
       - TTWJetsToQQ
       - TTGJets
       - TTWJetsToLNu
     Diboson:
       - WW
       - WZ
       - ZZ 
     WJets:
       - WJetsToLNu_HT-200To400
       - WJetsToLNu_HT-400To600
       - WJetsToLNu_HT-600To800
       - WJetsToLNu_HT-800To1200
       - WJetsToLNu_HT-1200To2500
       - WJetsToLNu_HT-2500ToInf
       - WJetsToQQ_HT400to600
       - WJetsToQQ_HT600to800
       - WJetsToQQ_HT800toInf
     ST:
       - ST_s-channel_4f_leptonDecays
       - ST_t-channel_top_4f_InclusiveDecays
       - ST_t-channel_antitop_4f_InclusiveDecays
       - ST_tW_top_5f_inclusiveDecays
       - ST_tW_antitop_5f_inclusiveDecays
     QCD:  
       - QCD_HT500to700
       - QCD_HT700to1000
       - QCD_HT1000to1500
       - QCD_HT1500to2000
       - QCD_HT2000toInf  
     ZandDY:
       - ZJetsToQQ_HT400to600
       - ZJetsToQQ_HT600to800 
       - DYJetsToLL_M-50
     TTbar:
       - TTToHadronic
       - TTToSemiLeptonic
       - TTTo2L2Nu
     TTHtoNonbbandTHW:
       - TTHtoNonbb
       - THW            



